--MEMBUAT VARIABLE
--CARA PERTAMA
DECLARE @Nilai INT = 100;
PRINT @Nilai;

--CARA KEDUA
DECLARE @Nama CHAR(255);
SET @Nama = 'NOVAL';
PRINT @Nama;

--MEMBUAT IF ELSE
--SAYA INGIN JIKA NILAINYA DIATAS 70 DIA LULUS
--JIKA TIDAK GAK LULUS
DECLARE @Nilai INT = 100;
IF @Nilai > 70
	PRINT 'Lulus';
ELSE
	PRINT 'Tidak Lulus';

--BUATKAN KONDISI JIKA HARGA BARANG
--LEBIH DARI 100.000, MAKA TAMPILKAN 'MAHAL'
--JIKA TIDAK, MAKA TAMPILKAN 'BELI'
DECLARE @Harga INT = 101000;
IF @Harga > 100000
	PRINT 'MAHAL';
ELSE
	PRINT 'BELI';

--VIEW
USE KampusDB
CREATE OR ALTER VIEW vw_Ruangan
AS
SELECT
	KodeRuangan,
	Gedung,
	Kapasitas
FROM Ruangan;

SELECT *
FROM vw_Ruangan;

--BUATKAN SEBUAH VIEW YANG DIMANA
--KETIKA DIPANGGIL ITU MENAMPILKAN
--NAMA MAHASISWA DAN JUGA SEMESTER YANG DIAMBIL

CREATE OR ALTER VIEW vw_Mahasiswa
AS
SELECT
M.NamaMahasiswa,
K.Semester
FROM Mahasiswa M
JOIN KRS K
ON M.MahasiswaID = K.MahasiswaID

SELECT *
FROM vw_Mahasiswa